IF EXISTS(SELECT name FROM sys.databases
    WHERE name = 'TripperDB')
    DROP DATABASE TripperDB
GO

CREATE DATABASE TripperDB;
GO

USE TripperDB;
GO

  
	CREATE TABLE dbo.Trip
	(
	 TripID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	 Name VARCHAR(50) NOT NULL,
	 DepartureTime DATETIME NOT NULL,
	 Budget DECIMAL(10,2) DEFAULT 0 NOT NULL,
	 EstimatedCost DECIMAL(10,2) DEFAULT 0 NOT NULL,
	 ModifiedDate DATETIME DEFAULT GETDATE() NOT NULL,
	 CreateDate DATETIME DEFAULT GETDATE() NOT NULL
	 )


	CREATE TABLE dbo.Country
	(
	CountryID TINYINT IDENTITY(1, 1) PRIMARY KEY  NOT NULL,
	Name VARCHAR(50) UNIQUE NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE() NOT NULL,
	) 


	CREATE TABLE dbo.Localization
	(
	LocalizationID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	City VARCHAR(50) NOT NULL,
	CountryID TINYINT NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE() NOT NULL,
	CONSTRAINT FK_CountryID FOREIGN KEY(CountryID) REFERENCES Country(CountryID)
	)

	CREATE TABLE dbo.Stayment
	(
	 StaymentID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	 Name VARCHAR(50) NOT NULL,
	 DateFrom DATETIME NOT NULL,
	 DateTo DATETIME NOT NULL,
	 TripID INT NOT NULL,
	 LocalizationID INT NOT NULL,
	 Cost DECIMAL(10,2) DEFAULT 0 NOT NULL,
	 ModifiedDate DATETIME DEFAULT GETDATE() NOT NULL,
	 CreateDate DATETIME DEFAULT GETDATE() NOT NULL,
	 CONSTRAINT FK_TripStayment FOREIGN KEY(TripID) REFERENCES Trip(TripID),
	 CONSTRAINT FK_LocationStayment FOREIGN KEY(LocalizationID) REFERENCES Localization(LocalizationID),
	 )


	CREATE TABLE dbo.Vehicle
	(
	VehicleID TINYINT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	Name VARCHAR(50) UNIQUE NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE() NOT NULL
	)


	CREATE TABLE dbo.Transport
	(
	TransportID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	Cost DECIMAL(10,2) DEFAULT 0 NOT NULL,
	IsReturn BIT DEFAULT 0 NOT NULL,
	TripID INT NOT NULL,
	VehicleID TINYINT NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE() NOT NULL,
	CreateDate DATETIME DEFAULT GETDATE() NOT NULL,
	CONSTRAINT FK_TripTransport FOREIGN KEY(TripID) REFERENCES Trip(TripID),
	CONSTRAINT FK_Vehicle_Ticket FOREIGN KEY(VehicleID) REFERENCES Vehicle(VehicleID)
	)


	CREATE TABLE dbo.Ticket
	(
	TicketID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	Seats VARCHAR(10) NULL,
	DepartureTime DATETIME NOT NULL,
	ArrivalTime DATETIME NOT NULL,
	TransportID INT NOT NULL,
	DepartureLocalization INT  NOT NULL,
	ArrivalLocalization INT  NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE() NOT NULL,
	CreateDate DATETIME DEFAULT GETDATE() NOT NULL,
	CONSTRAINT FK_TransportTicket FOREIGN KEY(TransportID) REFERENCES Transport(TransportID),
	CONSTRAINT FK_LocationDeparture FOREIGN KEY(DepartureLocalization) REFERENCES Localization(LocalizationID),
	CONSTRAINT FK_LocationArrival FOREIGN KEY(ArrivalLocalization) REFERENCES Localization(LocalizationID)
	)